
POST http://localhost:4000/auth/login HTTP/1.1
Content-Type: application/json

{
  "username": "test",
  "password": "1234"
}

###

POST http://localhost:4000/auth/refresh-token HTTP/1.1
Content-Type: application/json

{
  "token": 
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ikl2YW4iLCJyb2xlIjoidXNlciIsImVtYWlsIjoiaXZhbkBnbWFpbC5jb20iLCJwaG9uZSI6IiszNzM2OTcwNzkxMSIsImlhdCI6MTYwMjM1MzEyNH0.Y_Wfit7LB5Gb6GRQnxvKSlvyVYFazrWqTy_tEc6yDFY"
}

###

DELETE  http://localhost:4000/auth/logout HTTP/1.1
Content-Type: application/json

{
  "userId": 1
}

###

POST http://localhost:4000/database/create HTTP/1.1
Content-Type: application/json

{
  "database": "getlab"
}

###

POST http://localhost:4000/database/create-table-users HTTP/1.1
Content-Type: application/json

{}

###

POST http://localhost:4000/fill-database/user HTTP/1.1
Content-Type: application/json

{
  "name": "Ivan",
  "username": "uname",
  "password": "1234",
  "email": "ivan@gmail.com",
  "phone": "+37369707911"
}
###

GET http://localhost:4000/users/get-all 
access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ikl2YW4iLCJyb2xlIjoidXNlciIsImVtYWlsIjoiaXZhbkBnbWFpbC5jb20iLCJwaG9uZSI6IiszNzM2OTcwNzkxMSIsImlhdCI6MTYwMjM1MzEyNCwiZXhwIjoxNjAyMzUzNzI0fQ.ur4k4JFUKDrTu7GGjaYfKSOnRkh7p6wT6KyyyjN5Hn8

###

GET http://localhost:4000/auth/check-auth

###

POST http://localhost:4000/auth/sign-up HTTP/1.1
Content-Type: application/json

{ "name": "test2", "role": "user", "username": "test2", "password": "1234", "email": "ivi@gmail.com", "phone": "+37368212577" }

###

POST  http://localhost:4000/message/send HTTP/1.1
Content-Type: application/json
access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6Ikl2YW4iLCJyb2xlIjoidXNlciIsImVtYWlsIjoiaXZpQGdtYWlsLmNvbSIsInBob25lIjoiKzM3MzY4MjEyNTc3IiwiaWF0IjoxNjA0MjY2ODA5LCJleHAiOjE2MDQyNjc0MDl9.GTAbjqxqFWyTAH7ljEnNpUW_UKOzxM4HeU0VJsQzWUc

{
  "userId": 1,
  "message": "helloooou",
  "chatId": 6
}

###

GET  http://localhost:4000/message/last-message HTTP/1.1
Content-Type: application/json
access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ikl2YW4iLCJyb2xlIjoidXNlciIsImVtYWlsIjoiaXZpQGdtYWlsLmNvbSIsInBob25lIjoiKzM3MzY4MjEyNTc3IiwiaWF0IjoxNjA2MjAyNDE0LCJleHAiOjE2MDYyMDg0MTR9.ndZHLj7TsBeokZdHKG9uX2BmxcQykE9a5wa4HmAbAVQ

{
  "chatIds": [1, 2]
}

###

POST http://localhost:4000/chats/create HTTP/1.1
Content-Type: application/json
access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6InRlc3QyIiwicm9sZSI6InVzZXIiLCJlbWFpbCI6Iml2aUBnbWFpbC5jb20iLCJwaG9uZSI6IiszNzM2ODIxMjU3NyIsImlhdCI6MTYwNTc3MjExOCwiZXhwIjoxNjA1Nzc4MTE4fQ.P7AhsxmL2DwrG6BJdv4pll1GNDClxGXBZrjhwtv83Qk

{
  "userIds": [1,2]
}

###

POST http://localhost:4000/message/send HTTP/1.1
Content-Type: application/json
access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6InRlc3QyIiwicm9sZSI6InVzZXIiLCJlbWFpbCI6Iml2aUBnbWFpbC5jb20iLCJwaG9uZSI6IiszNzM2ODIxMjU3NyIsImlhdCI6MTYwNTc3MjExOCwiZXhwIjoxNjA1Nzc4MTE4fQ.P7AhsxmL2DwrG6BJdv4pll1GNDClxGXBZrjhwtv83Qk

{
  "chatId": "1",
  "msg": "Test message"
}

###

GET http://localhost:4000/university/universities HTTP/1.1
Content-Type: application/json
access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ikl2YW4iLCJyb2xlIjoidXNlciIsImVtYWlsIjoiaXZpQGdtYWlsLmNvbSIsInBob25lIjoiKzM3MzY4MjEyNTc3IiwiaWF0IjoxNjA2MDUwNDMyLCJleHAiOjE2MDYwNTY0MzJ9.38hCJRkhrwy3TrUssdSxZnN77Whd57ED0j14ji8fcnE
###

GET http://localhost:4000/university/faculties/1 HTTP/1.1
Content-Type: application/json
access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ikl2YW4iLCJyb2xlIjoidXNlciIsImVtYWlsIjoiaXZpQGdtYWlsLmNvbSIsInBob25lIjoiKzM3MzY4MjEyNTc3IiwiaWF0IjoxNjA2MDUwNDMyLCJleHAiOjE2MDYwNTY0MzJ9.38hCJRkhrwy3TrUssdSxZnN77Whd57ED0j14ji8fcnE
###

GET http://localhost:4000/university/groups/1 HTTP/1.1
Content-Type: application/json
access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Ikl2YW4iLCJyb2xlIjoidXNlciIsImVtYWlsIjoiaXZpQGdtYWlsLmNvbSIsInBob25lIjoiKzM3MzY4MjEyNTc3IiwiaWF0IjoxNjA2MDUwNDMyLCJleHAiOjE2MDYwNTY0MzJ9.38hCJRkhrwy3TrUssdSxZnN77Whd57ED0j14ji8fcnE
